### PR TITLE
SDK-1430: add test to verify sidechain nodes can still create certificates when mc nodes are offline

### PR DESCRIPTION
**Pull request by paologalligit**
## Description
Add test to verify sidechain nodes can still create certificates when the mainchain nodes their connected to temporarily are offline

## Jira Ticket
[SDK-1430](https://horizenlabs.atlassian.net/browse/SDK-1430)

## Changes
Add test to verify sidechain nodes can still create certificates when the mainchain nodes their connected to temporarily are offline

## Breaking Changes
No breaking changes

## Checks
- [x] Project Builds
- [x] Project passes tests and checks
- [x] Updated documentation accordingly

[SDK-1430]: https://horizenlabs.atlassian.net/browse/SDK-1430?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by rushby — COMMENTED** [review]
I think we should consider how to simulate the MC node deprecation, and the use of old and new versions of ZEND.  It's not something we currently cover in any of the tests

**Review by MarcoOl94 — APPROVED** [review]

**Comment by paologalligit** [comment]
> I think we should consider how to simulate the MC node deprecation, and the use of old and new versions of ZEND. It's not something we currently cover in any of the tests

That's interesting, but this can be something we can have in a different test case. We've found an issue where the previous certificate is deleted from the storage and cannot be retrieved anymore, so the zend deprecation should not be a problem. A brief description [here](https://horizenlabs.atlassian.net/browse/SDK-1430)

**Comment by paologalligit** [comment]
Converting current PR into a draft since the fix has not been decided yet

**Comment by paolocappelletti** [comment]
remember to add the new test to run_sc_tests.sh whenever we insert a new one
(I've added it)

**Pull request merged**
