### PR TITLE
Run tests in parallel

### PR DESCRIPTION
**Pull request by rushby**
Run tests in parallel by specifying -parallel flag with an integer value.

### CODE REVIEW

**Comment by JcBernack** [comment]
Question for my understanding: Is this splitting the tests into N sets and starting an individual process per test?

If that is the case, some sets might finish way faster than others and we lose some parallelism. Would it be possible to have a pool of N processes each executing one test at a time until all of them are done?

**Comment by rushby** [comment]
@JcBernack Script has now been refactored to be more efficient and run each test from the same list as a process becomes available

**Comment by JcBernack** [comment]
Not a review of the code, just a test run:
```
❯ ./run_sc_tests.sh -parallel=8 -evm_only
Running test "sc_evm_bootstrap.py" (1 of 44) in parallel group: 1
Running 1 Of 44 Tests :: Parallel Group 1 ::
=== Running testscript sc_evm_bootstrap.py === (Parallel Group: 1)
Running test "sc_evm_eoa2eoa.py" (2 of 44) in parallel group: 2
Running 2 Of 44 Tests :: Parallel Group 2 ::
=== Running testscript sc_evm_eoa2eoa.py === (Parallel Group: 2)
Running test "sc_evm_forward_transfer.py" (3 of 44) in parallel group: 3
Running 3 Of 44 Tests :: Parallel Group 3 ::
=== Running testscript sc_evm_forward_transfer.py === (Parallel Group: 3)
Running test "sc_evm_backward_transfer.py" (4 of 44) in parallel group: 4
Running 4 Of 44 Tests :: Parallel Group 4 ::
=== Running testscript sc_evm_backward_transfer.py === (Parallel Group: 4)
Running test "sc_evm_backward_transfer_2.py" (7 of 44) in parallel group: 7
Running 7 Of 44 Tests :: Parallel Group 7 ::
=== Running testscript sc_evm_backward_transfer_2.py === (Parallel Group: 7)
!!! FAIL: sc_evm_bootstrap.py !!! ### Run Time: 23(s) ###

--- Success: sc_evm_forward_transfer.py --- ### Run Time: 28(s) ###

Running test "sc_evm_base_fee.py" (10 of 44) in parallel group: 3
Running 10 Of 44 Tests :: Parallel Group 3 ::
=== Running testscript sc_evm_base_fee.py === (Parallel Group: 3)
--- Success: sc_evm_eoa2eoa.py --- ### Run Time: 33(s) ###

Running test "sc_evm_bwt_corner_cases.py" (11 of 44) in parallel group: 2
Running 11 Of 44 Tests :: Parallel Group 2 ::
=== Running testscript sc_evm_bwt_corner_cases.py === (Parallel Group: 2)
```

- I expected 8 parallel tests with `-parallel=8`, but it looks like there are less than that.
  ```
  gigo      172937  0.0  0.0  19908  3976 pts/0    S<+  22:16   0:00 /bin/bash ./run_sc_tests.sh -parallel=8 -evm_only
  gigo      172940  0.0  0.0  19908  2988 pts/0    S<+  22:16   0:00 /bin/bash ./run_sc_tests.sh -parallel=8 -evm_only
  gigo      172941  0.0  0.0  19908  2988 pts/0    S<+  22:16   0:00 /bin/bash ./run_sc_tests.sh -parallel=8 -evm_only
  gigo      172942  0.0  0.0  19908  2988 pts/0    S<+  22:16   0:00 /bin/bash ./run_sc_tests.sh -parallel=8 -evm_only
  gigo      172947  0.0  0.0  19908  2988 pts/0    S<+  22:16   0:00 /bin/bash ./run_sc_tests.sh -parallel=8 -evm_only
  gigo      172949  0.0  0.0  19908  2988 pts/0    S<+  22:16   0:00 /bin/bash ./run_sc_tests.sh -parallel=8 -evm_only
  gigo      172993  0.4  0.0  48724 27080 pts/0    S<+  22:16   0:00 python3 ./sc_evm_bootstrap.py --parallel=1
  gigo      173022  0.4  0.0  48920 27312 pts/0    S<+  22:16   0:00 python3 ./sc_evm_eoa2eoa.py --parallel=7
  gigo      173043  0.4  0.0  50152 28168 pts/0    S<+  22:16   0:00 python3 ./sc_evm_forward_transfer.py --parallel=2
  gigo      173066  0.5  0.0  50844 29360 pts/0    S<+  22:16   0:00 python3 ./sc_evm_backward_transfer.py --parallel=3
  gigo      173107  0.4  0.0  49220 27648 pts/0    S<+  22:16   0:00 python3 ./sc_evm_backward_transfer_2.py --parallel=6
  ```
- Sometimes tests still seem to fail randomly. In the example above see `sc_evm_bootstrap.py`. I ran that test on its own immediately afterwards and it ran successfully.
- After a while all the tests seem to be started in `parallel group: 7`. I see that there are other processes still running though.. I don't know what is happening. :thinking: 
- Logging messages seem a bit redundant currently. Three lines for each started test, saying the same thing twice. Could be reduced to one line.

**Review by i-Alex — CHANGES_REQUESTED** [review]
PR looks amazing!
Let's update `qa/readme.md` file and put some info about the parallel execution flag.

**Review by i-Alex — APPROVED** [review]

**Pull request merged**
