### PR TITLE
nm/evm 323 python stf fix

### PR DESCRIPTION
**Pull request by rockNicktive**
Contains jb/truffle-fixes up to this point

### CODE REVIEW

**Review by i-Alex — CHANGES_REQUESTED** [review]
Some Python tests are still failing:
1) sc_evm_bootstrap.py
2) sc_evm_estimateGas.py
3) sc_evm_test_debug_methods.py
4) sc_evm_test_metamask_related.py

**Comment by rockNicktive** [comment]
> Some Python tests are still failing:
> 
> 1. sc_evm_bootstrap.py
> 2. sc_evm_estimateGas.py
> 3. sc_evm_test_debug_methods.py
> 4. sc_evm_test_metamask_related.py

sc_evm_bootstrap.py runs fine for me and results in `Test successful`, can you give me the erroneous output?

**Review by i-Alex — APPROVED** [review]
Looks good!
@GitMark0 pls take a look at `sc_evm_test_debug_methods.py` and fix in the separate branch on top of this one.

**Comment by i-Alex** [comment]
Fix for `sc_evm_test_debug_methods.py` was merged

**Pull request merged**
